import "./articlesPage.css";

function ArticlesPage(props){
    return(
        <div id={props.articlesClicked===false?"none":"articlesPageParentDiv"}>
            <h4>5 Steps For Giving De-Wormer To Horses</h4>
            <p>I have found that most people's horses resist taking de-wormer because they usually force the horse to take it. The steps below work for any horse (even resistant horses). Repeat each step (not moving onto the next one) until the horse does it relaxed and thinking, instead of reacting:</p>
            <p>1. Approach and retreat placing your finger on the lips of your horse's mouth near their interdential gap.</p>
            <p>2. Approach and retreat placing your finger inside your horse's mouth at the interdential gap, touching the tounge.</p>
            <p>Now we're repeating the steps above, but with the syringe instead of your finger.</p>
            <p>3. With de-wormer in hand (keep cap on the syringe), approach and retreat placing the syringe on the lips of your horse's mouth near their interdential gap.</p>
            <p>4. With de-wormer in hand (keep cap on the syringe), approach and retreat placing the syringe inside your horse's mouth at the interdential gap, touching the tounge.</p>
            <p>5. Remove cap from de-wormer syringe and slide it into the horse's interdential gap. Quickly squeeze desired de-wormer paste into the horse's mouth.</p>
            <h4>Training Abused Horses</h4>
            <p>I have found that abused horses only need to be re-taught two things. This article explains these two two ways of thinking that horses have to re-adapt. After these two lessons, all abused horses are ready to make progress in training.</p>

            <h4>Lesson 1: Understand Pressure</h4>
            <p>Horses that have been abused are often used to people escalating pressure with no chance for the horse to try to find the release of pressure. For example, someone could be standing by their horse (let's say that pressure has a scale of 1-10) with a pressure of 0, and the horse pushes the person with their head. An abusive person adds pressure that is so intese and high with a pressure of 9 or 10 to get the horse to stop pushing them with their head. Horses don't know how to deal with this type of abusive communication because horses never jump from a 0 to a 10 with one another in their herds. They always increase their pressure through each number, to give the other horse a fair warning to start looking for the release of pressure. Horses increase pressure gradually with ourward signs like: Swishing tail (1-2), pinning ears (3-4), biting (5-6), pushing with butt (7-8), 9(single leg kicks), 10(kicking with both rear legs). They never skip these steps, so they have an impossible time understanding humans that do skip steps.</p>

            <p>When training an abused horse, the first 3-4 days are to teach the horse that humans do use gradual amounts of pressure, and that we will give time for them to think through a problem and find the release of pressure. Some horses that have been abused either act out in defence when humans are not doing anything threatening, because the horse is scared that we are going to be unrational with our pressure. Some abused horses lock up and ignore the pressure that a human is giving them, because they know that if they move at all, they might get hurt from the owner. These problems are easily trained out of abused horses, and don't effect their training or life permenantly.</p> 
            <h4>Lesson 2: Relaxful mind</h4>
            <p>Horses that have been abused, haven't learned to be relaxed. They also haven't learned to thing through pressure while being relaxed. Once a horse has learned to be relaxed while thinking through problems, it will no longer show the previously extreme reactions to being trained or taught. This relaxful mindset takes a lot of time to teach an abused horse. It takes somewhere between 4 weeks to 4 months depending on the amount of times the horse has been abused.</p>
            <h4>Object Desensitization vs. Location Desensitization</h4>
            <p>Which gets a queiter and relaxed horse quicker, desensitizing to objects or locations?</p>
            <p>Desensitizing a horse to a variety of objects is limited to the objects that are in your possesion while with the horse. Location desensitization gets horses quieter because not only does it make them relax with a new location, they also have to relax to the random and ever-changing objects that are in the location. This is why trail rides are so effective for getting horses calm in all sorts of situations. When on the trail, you get a horse desensitized to locations and objects, while the alternative only trains them to be comfortable with objects.</p>
            <p>Horses might be comfortale with a plastic bag in their stall, but then when they see a plastic bag on the sidewalk they are apprehensive about it again. This is because horses don't assume that because one plastic bag was safe, that all plasitc bags will be safe. They will be apprehensive to a familiar object, if the location of it is new. Desensitizing horses to objects can prove to be a waste of time, if they aren't also being desensistized to locations just as much.</p>
            <h4>Teaching Horses To Think About Scary Objects, Instead Of Repatitiously Proving That The Object Won't Hurt Them</h4>
            <p>Many horses don't know how to think about if something should be scary or if it is safe. Most horses just assume that the object isn't safe, if they haven't had high amounts of safe exposure to that type of object. This is why it is important that horses don't experience high amounts of stress and pressure every time they are getting trained. A good trainer will only stress and pressure their horse about once every two weeks. This will re-affirm the horse's emotions to stay stable and not escalate at every new form of pressure. This also fosters an environment where horses enjoy being and are relaxed during the learning process. If a person is pushing a horse to do high levels of performance every day, then that horse isn't going to like being around that person.</p>
        </div>
    );
};
export {ArticlesPage};